config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :questions do
    resources :answers
  end
  resources :users

  root to: 'questions#index'
  end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

   def new
      @question = Question.find(params[:question_id])
      @answer = @question.answers.build
   end

   def create
     @question = Question.find(params[:question_id])
     @answer = @question.answers.create(answer_params)
     @answer.user_id = current_user.id

     if @answer.save
      redirect_to question_path(@question)
     else
      redirect_to root_path
    end
   end



   def edit
     @question = Question.find(params[:question_id])
     @answer = @question.answers.find(params[:id])
   end

   def update
     @question = Question.find(params[:question_id])
     @answer = @question.answers.find(params[:id])
     if @answer.update(answer_params)
      redirect_to question_path(@question)
     else
      render 'edit'
     end
   end

    def destroy
     @question = Question.find(params[:question_id])
     @answer = @question.answers.find(params[:id])
     @answer.destroy
     redirect_to question_path(@question)

    end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit #GET
    if current_user
    @question = Question.find(params[:id])
    end
  end

  def update #patch
    @question = Question.find(params[:id])
      if @question.update(question_params)
        redirect_to root_path
      else
        redirect_to edit_question_path
      end
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.all.order('created_at DESC')
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash.now[:danger] = "Question deleted!"
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create

  end

  def show

  end

  def index
    @users = User.all
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<ul>
<li><P><%= answer.content %></P></li>
<li class="signature">Posted by <%= answer.user.name %> <%= time_ago_in_words(answer.created_at) %> ago</li>
<% if answer.user_id == current_user.id %>
<li><%= link_to "Edit", edit_question_answer_path(answer.question, answer) %> |
<%= link_to "delete", question_answer_path(answer.question, answer), method: :delete,
data: { confirm: "Are you sure?"} %></li>
<% end %>
</ul>
<br>

app/views/answers/_form.html.erb
<%= simple_form_for([@question, @question.answers.build]) do |a| %>
  <%= a.input :content, label: "Type your answer here" %>
  <%= a.button :submit %>
<% end %>

app/views/answers/edit.html.erb
<h3>Edit Answer</h3>

<%= simple_form_for ([@question, @answer])  do |e| %>

  <%= e.input :content, label: "Answer" %>
  <%= e.button :submit %>
  <% end %>

app/views/answers/index.html.erb
<% @answers.each do |a| %>

<%= a.content %>

  <% end %>

app/views/answers/new.html.erb
<h1><%= @question.body %></h1>
<%#= question.body %>
<%= render 'form' %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand fa fa-2x fa-telegram" href="#"></a>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "Ask a question", new_question_path %></a></li>
        <li><%= link_to "Index", questions_path %></a></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
       <!-- <li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if current_user %>
            <li><%= link_to "Edit #{current_user.name}", edit_user_registration_path %></li>
            <li><%= link_to "All Users", user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A Sample Forum app</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <div class="jumbotron">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |q| %>
  <%= q.input :body, label:"Question du jour" %>
  <%= q.button :submit %>
<% end %>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit your question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
    <div class="text-center"><h1>Questions</h1></div><br>

    <% @questions.each do |q| %>
      <ul>
        <li><h3><%= link_to(q.body, question_path(q)) %></h3></li>
        <li class="signature">by: <%= q.user.name %></li><br>
          <% q.answers[0..1].each do |a| %>
            <ul>
              <li><%= a.content %></li>
              <li class="signature">Posted by <%= a.user.name %> <%= time_ago_in_words(a.created_at) %> ago</li>
            </ul>
            <ul>
              <li>.....</li>
            </ul>
            <br>
          <% end %>
          <% if user_signed_in? %>
          <% if current_user.id == q.user_id %>
            <li><%= link_to "Delete", question_path(q),
            method: :delete, data: { confirm: 'Are you sure ?' } %> |
             <%= link_to "Edit", edit_question_path(q) %> |
           <% end %>
         <% end %>
        <%= link_to "Answer", new_question_answer_path(q) %></li>
      </ul>

    <% end %>

app/views/questions/new.html.erb
<h1>Ask a question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h2><%= @question.body %></h2>
<li class="signature">Posted by <%= @question.user.name %> <%= time_ago_in_words(@question.created_at) %> ago </li>

<br>
<br>
<%= render @question.answers %> <br>
<%= render 'answers/form' %>

app/views/users/index.html.erb
<h1>All users</h1>

<% @users.each do |user| %>
  <p><%= user.email %> | <%= user.name %></p>

<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>